[project]
name = "huggingfaceagents-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "gradio>=5.31.0",
    "ipykernel>=6.29.5",
    "pytz>=2025.2",
    "ruff>=0.11.11",
    "smolagents[litellm]>=1.16.1",
    "transformers>=4.52.3",
]
