[project]
name = "huggingfaceagents-course"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.11",
    "smolagents[litellm]>=1.16.1",
]
